### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by miriammalka** [miriammalka/memorygame#1]

**Comment by miriammalka** [comment]
[Spec for Memory Game (2).txt](https://github.com/miriammalka/memorygame/files/10670142/Spec.for.Memory.Game.2.txt)

This is my Spec. I took the How To Git course, but I am still not 100% sure exactly what I am supposed to do. I was told I should put my spec in an issue in my game repo and then share the link to that issue with CPU staff.

**Comment by AshiraFriedman** [comment]
Wow!  Great job, really nice spec!
The way you did it looks good, I just need you to add me as a collaborator to your repo and game project - you can see pdf instructions in session 13 how to do that.

**Comment by miriammalka** [comment]
Ok, will do. Thank you so much!

**Comment by miriammalka** [comment]
I see that I made my spec a bit to hard for myself. Can you help me? Can I change my spec a little bit to make it easier for myself if you are not able to help me? It will mean I will have to change my wireframe a bit.

**Comment by AshiraFriedman** [comment]
I responded in slack, we can discuss there

**Comment by miriammalka** [comment]
[Spec for Memory Game (3).txt](https://github.com/miriammalka/memorygame/files/10809732/Spec.for.Memory.Game.3.txt)

I'm resubmitting my spec because I made the changes I spoke to you about.

**Comment by AshiraFriedman** [comment]
Looks good!
