### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by miriammalka** [miriammalka/memorygame#2]

**Comment by miriammalka** [comment]
This is the link to my wireframe. Would it be ok if my version in Visual Studio would not be the exact same colors as this one? The layout would still be the same.
https://app.moqups.com/sGH8nmyy6L2gqbfuCjMbFe7qwyy8d2c7/view/page/ad64222d5

**Comment by miriammalka** [comment]
I'll also upload it as an image if
![Page](https://user-images.githubusercontent.com/97982214/217706064-30c0e796-09d5-47ae-9b53-c85320256842.png)
 that is better.

**Comment by AshiraFriedman** [comment]
Great!  Looks really nice!
Yes, it's fine if they are not the exact same colors
