### ISSUE TITLE
Bug on game completion

### ISSUE THREAD

**Issue by AshiraFriedman** [miriammalka/memorygame#4]
When game is completed, the last match stays on the screen and those cards remain turned over. Please fix this

**Comment by miriammalka** [comment]
I left them on the screen because then of you want to start a new game you
just press start again and then the whole board is reset

**Comment by miriammalka** [comment]
please let me know as soon as possible if I sufficiently fixed the problem.

**Comment by miriammalka** [comment]
I realized I had to fix one more thing

**Comment by miriammalka** [comment]
I'm sorry I committed so many times. Please ignore my previous commits and just look at my most recent one. I kept realizing I had to fix something but this should be all good to go.

**Comment by AshiraFriedman** [comment]
Great job!
All looks good
